zeebe:
  client:
    broker.contactPoint: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S

spring:

  datasource:
    url: jdbc:mysql://dev-alarm:17878/zeebe?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 111111
    driverClassName: com.mysql.jdbc.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    root: DEBUG
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN
