zeebe:


  client:
    broker.contactPoint: 127.0.0.1:26500
    security.plaintext: true

    worker:
      hazelcast:
        connection: localhost:5701
        connectionTimeout: PT30S
      kafka:
        consumer:
          servers: "localhost:9092"
          groupId: "test_group_1"
          topicPattern: "^zeebe.*$"
          config: |
            linger.ms=5
            buffer.memory=8388608
            batch.size=32768
            max.block.ms=5000

  # zeebe exporter 类型， kafka/hazelcast
  exporter: "kafka"

spring:

  datasource:
    url: jdbc:h2:mem:zeebe-monitor;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    expose-request-attributes: true

  data:
    web:
      pageable:
        default-page-size: 10

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.monitor: DEBUG
    com.hazelcast: WARN
